Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: CICD
 
 on:
@@ -9,39 +6,36 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - name: Checkout Source Code
-    - uses: actions/checkout@v4
+      uses: actions/checkout@v4
 
     - name: Create .env file
-    - run: |
+      run: |
         touch .env
         echo "${{ secrets.PRODUCTION_ENV_SECRET }}" > .env
     
     - name: Sign in to Docker Hub
-    - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
     
     - name: Build Docker Image
-    - run: docker build -t HangA-Kim/keyword_finder_public .
+      run: docker build -t HangA-Kim/keyword_finder_public .
       
     - name: Push Docker Image
-    - run: docker push HangA-Kim/keyword_finder_public:latest
+      run: docker push HangA-Kim/keyword_finder_public:latest
     
-  # deploy:
-  #   needs: build
-  #   runs-on: aws-ec2 
-    # steps:
-    #   - name: Pull image from docker hub
-    #   - run: docker pull HangA-Kim/keyword_finder_public:latest
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Pull image from docker hub
+      run: docker pull HangA-Kim/keyword_finder_public:latest
         
-    #   - name: Delete existing container
-    #   - run: docker rm -f reactContainer
+    - name: Delete existing container
+      run: docker rm -f reactContainer || true  # if no container exists, don't fail
         
-    #   - name: Run container
-    #   - run: docker run -d -p 80:80 --name reactContainer HangA-Kim/keyword_finder_public
-
-
-
+    - name: Run container
+      run: docker run -d -p 80:80 --name reactContainer HangA-Kim/keyword_finder_public
